### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by purcell**
Hey, I'm considering this as an alternative to the venerable `highlight-symbol`, and thought I'd send along a few fixes that would be necessary to that end. :-)

### CODE REVIEW

**Comment by wolray** [comment]
Merged, thanks for all your fixes and improvements.

After this merge, the package should be much easier for users to customize especially for those who are not familiar with elisp.

Besides, I am a little curious that is the group `convenience`  is a public group consisting of various settings from different packages? 

And, is there anything I can do to make more people use `symbol-overlay`? It could be very helpful if you had any suggestions for me.

**Comment by purcell** [comment]
> Merged, thanks for all your fixes and improvements.

Happy to help.

> After this merge, the package should be much easier for users to customize especially for those who are not familiar with elisp.

👍 

> Besides, I am a little curious that is the group convenience is a public group consisting of various settings from different packages?

Yes. There are a few built-in top-level customisation groups, and it's conventional to place your package inside one for customisation purposes.

> And, is there anything I can do to make more people use symbol-overlay? It could be very helpful if you had any suggestions for me.

I've just committed it to my config in place of `highlight-symbol`, and lots of people use that. So I guess that'll help. If I come across any more fixes or suggestions that would be useful, I'll let you know.

**Comment by wolray** [comment]
Thanks for your quick respond.

There seems to be a problem. When I trigger `symbol-overaly-mode` for the first time after starting emacs, an error shows up:
`face-spec-recalc: Wrong type argument: listp, t`

Then if I continue moving cursors with the mode on, no color face will appear on the symbol at point.

Could it be something wrong with the `defface` of `symbol-overlay-temp-face`?

**Comment by purcell** [comment]
Yep, https://github.com/wolray/symbol-overlay/pull/9 fixes this. :-)

**Comment by wolray** [comment]
Ok, problem solved. :-)

**Comment by wolray** [comment]
Really a good solution for auto-setting the temp-face in both light and dark themes.

**Comment by purcell** [comment]
Yep, it's generally a good plan to `:inherit` from built-in faces wherever possible, because then the default appearance will be reasonable in most published themes.

**Pull request merged**
